### ISSUE TITLE
Make it possible to define multiple mapping for the same class

### ISSUE THREAD

**Issue by rogargon** [rogargon/data-mapping-tool-client#4]
For instance, if the data being mapped refers to multiple Measurements, make it possible to pick the class Measurement more than once and to define different mappings for each instance.

**Comment by jorgechp** [comment]
Should be fixed now.

**Comment by rogargon** [comment]
Still not working, at least at the UI component level. If I select "core.Measurement" as a mapping class, I cannot select it again. Picking it up again in the class autocomplete, it is deleted.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1313870/228922060-c661b30f-a5c5-4750-aba4-f7a893eabd6c.png">
